---
- name: Get the latest GitHub CLI release information
  community.general.github_release:
    user: cli
    repo: cli
    action: latest_release
  register: github_cli_release

- name: Latest GitHub cli version.
  ansible.builtin.debug:
    msg: Latest GitHub cli version {{ github_cli_release.tag }} arch-{{ deb_architecture[ansible_architecture] }} {{ ansible_distribution }}
  when: github_cli_release is defined

- name: Get GitHub cli version installed
  ansible.builtin.command: python3 --version
  register: py3ver
  changed_when: false

- name: Install the GitHub CLI from .deb package.
  # In the name of the release we need to strip to v from the `github_cli_release`.
  ansible.builtin.apt:
    deb:
      "https://github.com/cli/cli/releases/download/{{ github_cli_release.tag }}/\
      gh_{{ github_cli_release.tag | replace('v', '') }}_linux_{{ deb_architecture[ansible_architecture] }}.deb"
