---
- name: Configure server
  hosts: servers
  become: true

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include config override file, if it exists.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - config.yml
      tags: ['always']

    - name: Include init tasks
      ansible.builtin.import_tasks:
        file: tasks/init.yml
      tags: ['always']

  roles:
    - role: geerlingguy.security
      tags: ['security', 'ssh']

    - role: geerlingguy.firewall
      tags: ['security', 'firewall']

    - role: geerlingguy.git
      tags: ['git']

    - role: geerlingguy.pip
      tags: ['pip']

    - role: geerlingguy.docker_arm
      tags: ['docker']

    - role: appearance
      tags: ['appearance']

    - role: input_devices
      tags: ['input']

    - role: vscodium
      tags: ['apps', 'vscodium']

    - role: github_cli
      tags: ['apps', 'gh']

    - role: evolution
      tags: ['apps', 'evolution']

    - role: rclone
      tags: ['apps', 'rclone']

    # - role: dropbox
    #   tags: ['apps', 'dropbox']

    - role: cawbird
      tags: ['apps', 'cawbird']

    - role: mirage
      tags: ['apps', 'mirage']

    - role: pidgin
      tags: ['apps', 'pidgin']

    - role: sound_recorder
      tags: ['apps', 'sound_recorder']

  tasks: []
