---
- hosts: pi
  become: yes

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include config override file, if it exists.
      include_vars: "{{ item }}"
      with_fileglob:
        - config.yml
      tags: ['always']

    - import_tasks: tasks/init.yml

  roles:
    - role: geerlingguy.security
      tags: ['security', 'ssh']

    - role: geerlingguy.firewall
      tags: ['security', 'firewall']

    - role: geerlingguy.git
      tags: ['git']

    - role: geerlingguy.pip
      tags: ['pip']

    - role: geerlingguy.docker_arm
      tags: ['docker']

    - role: input_devices
      tags: ['input']

    - role: vscodium
      tags: ['apps', 'vscodium']

    - role: github_cli
      tags: ['apps', 'gh']

    - role: evolution
      tags: ['apps', 'evolution']

    - role: rclone
      tags: ['apps', 'rclone']

    # - role: dropbox
    #   tags: ['apps', 'dropbox']

    - role: cawbird
      tags: ['apps', 'cawbird']

    - role: mirage
      tags: ['apps', 'mirage']

  tasks: []
