---
- name: Configure server
  hosts: servers
  become: true

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include config override file, if it exists.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - config.yml
      tags: ['always']

    - name: Include init tasks
      ansible.builtin.import_tasks:
        file: tasks/init.yml
      tags: ['always']

  # Setup name mapping when installing from apt
  vars:
    deb_architecture: {
      "armv6l": "armhf",
      "armv7l": "armhf",
      "aarch64": "arm64",
      "x86_64": "amd64",
      "i386": "i386"
    }

  roles:
    - role: geerlingguy.security
      tags: ['security', 'ssh']

    - role: geerlingguy.firewall
      tags: ['security', 'firewall']

    - role: geerlingguy.git
      tags: ['git']

    - role: geerlingguy.pip
      tags: ['pip']

    - role: docker
      tags: ['docker']

    - role: geerlingguy.nfs
      tags: ['nfs-server']

    - role: vscodium
      tags: ['apps', 'vscodium']

    - role: github_cli
      tags: ['apps', 'gh']

  tasks: []
