---
- name: Configure server
  hosts: servers
  become: true

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include config override file, if it exists.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - config.yml
      tags: ['always']

    - name: Include init tasks
      ansible.builtin.import_tasks:
        file: tasks/init.yml
      tags: ['always']

  # Setup name mapping when installing from apt
  vars:
    deb_architecture: {
      "armv6l": "armhf",
      "armv7l": "armhf",
      "aarch64": "arm64",
      "x86_64": "amd64",
      "i386": "i386"
    }

  roles:
    - role: geerlingguy.security
      tags: ['security', 'ssh']

    - role: geerlingguy.firewall
      tags: ['security', 'firewall']

    - role: geerlingguy.git
      tags: ['git']

    - role: geerlingguy.pip
      tags: ['pip']

    - role: docker
      tags: ['docker']

    - role: geerlingguy.nfs
      tags: ['nfs-server']

    - role: vscodium
      tags: ['apps', 'vscodium']

    - role: github_cli
      tags: ['apps', 'gh']

  tasks: []

# For client
# Add nfs-common smbclient cifs-utils
# Configure mount point in /etc/fstab
# //192.168.110.17/data /media/NAS/data cifs noauto,iocharset=utf8,x-systemd.automount,uid=1000,gid=1000,forceuid,forcegid,credentials=/home/antoine/.creds/.diskstation_data,rw,vers=3.0 0 0

# 192.168.110.5:/mnt/external/nfs_jellyfin /mnt/external/nfs_jellyfin nfs nfsvers=4,resvport 0 0
