---
- name: Create a new regular user with sudo privileges
  ansible.builtin.user:
    name: "{{ created_username }}"
    state: present
    groups: sudo
    append: true
    create_home: true
    shell: /usr/bin/bash

- name: Set authorized key for remote user
  ansible.posix.authorized_key:
    user: "{{ created_username }}"
    state: present
    key: "{{ lookup('ansible.builtin.file', '{{ ansible_ssh_private_key_file }}.pub') }}"

- name: Update apt cache if needed.
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400

- name: Ensure /usr/local/bin exists.
  ansible.builtin.file:
    path: /usr/local/bin
    state: directory
    mode: "775"

- name: Ensure auth.log file is present.
  ansible.builtin.copy:
    dest: /var/log/auth.log
    content: ""
    force: false
    mode: "640"

- name: Ensure dependencies are installed.
  ansible.builtin.apt:
    name:
      - curl
      - openssh-server
      - openssh-client
      - libffi-dev
      - libssl-dev
      - cron
      - dnsutils
    state: present
