---
- name: Update apt cache if needed.
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400

- name: Ensure /usr/local/bin exists.
  ansible.builtin.file:
    path: /usr/local/bin
    state: directory
    mode: "775"

- name: Ensure auth.log file is present.
  ansible.builtin.copy:
    dest: /var/log/auth.log
    content: ""
    force: false
    mode: "640"

- name: Ensure dependencies are installed.
  ansible.builtin.apt:
    name:
      - curl
      - openssh-server
      - openssh-client
      - libffi-dev
      - libssl-dev
      - python-backports.ssl-match-hostname
      - cron
    state: present
