---
- name: Ensure dependencies are present.
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - gnupg
      - python3-debian
    state: present

- name: Add vscodium repo using key from URL.
  ansible.builtin.deb822_repository:
    name: vscodium
    types: [deb]
    uris: "https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs"
    suites: [vscodium]
    components: [main]
    signed_by: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    state: present
    enabled: true
  notify: Update apt cache

- name: Ensure apt cache is called if needed
  ansible.builtin.meta: flush_handlers

- name: Ensure VSCodium is installed.
  ansible.builtin.apt:
    name: codium
    state: present
