---
- name: Enable natural scrolling direction.
  blockinfile:
    path: /usr/share/X11/xorg.conf.d/40-libinput.conf
    block: |
      Section "InputClass"
          Identifier "libinput pointer catchall"
          MatchIsPointer "on"
          MatchDevicePath "/dev/input/event*"
          Driver "libinput"
          Option "NaturalScrolling" "true"
      EndSection
  notify: needs_reboot
