---
# Based on https://github.com/geerlingguy/ansible-role-docker
- name: Ensure old versions of Docker are not installed.
  ansible.builtin.package:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - podman-docker
      - containerd
      - runc
    state: absent

- name: Ensure dependencies are present
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - python3-debian
    state: present

- name: Add docker repo using key from URL.
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    suites: ["{{ ansible_distribution_release }}"]
    components: [stable]
    signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
    enabled: true
  notify: Update apt cache

- name: Ensure apt cache is called if needed
  ansible.builtin.meta: flush_handlers

- name: Ensure docker packages are installed
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-ce-rootless-extras
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Configure Docker daemon options
  ansible.builtin.copy:
    content: "{{ docker_daemon_options | to_nice_json }}"
    dest: /etc/docker/daemon.json
    mode: "644"
  when: docker_daemon_options.keys() | length > 0
  notify: Restart docker

- name: Ensure Docker is started and enabled at boot
  ansible.builtin.service:
    name: docker
    state: "started"
    enabled: true

- name: Ensure handlers are notified now to avoid firewall conflicts
  ansible.builtin.meta: flush_handlers

- name: Get docker group info using getent.
  ansible.builtin.getent:
    database: group
    key: docker
    split: ':'
  when: docker_users | length > 0

- name: Check if there are any users to add to the docker group
  ansible.builtin.set_fact:
    at_least_one_user_to_modify: true
  when:
    - docker_users | length > 0
    - item not in ansible_facts.getent_group["docker"][2]
  loop: "{{ docker_users }}"

- name: Ensure docker users are added to the docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"

- name: Reset ssh connection to apply user changes.
  ansible.builtin.meta: reset_connection
